api:
  v1: v3/api-docs

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?currentSchema=public&options=-c%20TimeZone=Asia/Seoul
    username: postgres
    password: postgres
  jackson:
    time-zone: Asia/Seoul
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  application:
    name: PAY-SERVICE

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 3s

  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      name: pay-service
      fail-fast: true
  batch:
    jdbc:
      initialize-schema: never
  task:
    scheduling:
      cron:
        settlement: ${SETTLEMENT_CRON:-}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, prometheus

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY:}
    success_url: ${TOSS_SUCCESS_URL:http://localhost:64432/study/study.main/static/payments/success.html}
    fail_url: ${TOSS_FAIL_URL:http://localhost:64432/study/study.main/static/payments/fail.html}
